
= Payment

An invoice represents a claim for payment. The issuance of an invoice may take place either before or after the payment is carried out. When an invoice is issued before payment it represents a request to the Buyer to pay, in which case the invoice commonly contains information that enables the Buyer, in the role of a debtor, to correctly initiate the transfer of the payment, unless that information is already agreed in prior contracts or by means of payment instructions separately lodged with the Buyer.

If an invoice is issued after payment, such as when the order process included payment instructions or when paying with a credit card, online or telephonic purchases, the invoice may contain information about the payment made in order to facilitate invoice to payment reconciliation on the Buyer side. An invoice may be partially paid before issuing such as when a pre-payment is made to confirm an order.

Invoices, conformant with this specification can identify the means of payment for settlement of the invoice and clearly state what payment amount is requested. 

Specifically three types of payment means are used for invoices in Singapore:

*	Direct debit using GIRO (PaymentMeans Code Z01
*	Credit Transfer using PayNow Corporate using the UEN as identification of the payee account. (PaymentMeans Code Z02)
*	Credit Card (PaymentMeans Code 54)

====
NOTE: PaymentMeans Codes Z01 and Z02 are not recoginized codes in UNCL4461. They have been added in the Singapore extension of Peppol BIS Billing 3.
====

Detailed requirements for supporing payment functionality can be found at <<paymentreq>>
