
= Introduction to openPEPPOL and BIS

[preface]
This specification is an extension of the PEPPOL BIS Billing 3.0 specification, following the guidance given in TR 16931-5 “Guidelines on the use of sector or country extensions in conjunction with EN16931-1” Any instance documents compliant to this specification will be conformant to the PEPPOL BIS Billing 3.0 and to the European Standard EN 16931.

The main requirement for the extensions comes from the fact that Singapore uses Goods and Service Tax (GST) instead of Value Added Tax (VAT). This has consequences on code lists and the naming of some business terms.

On a syntactical level, this specification only uses the OASIS UBL 2.1 XML format.

A {peppol} BIS provides a set of specifications for implementing a {peppol} business process. A BIS document is concerned with clarifying requirements for ensuring interoperability of pan-European Public eProcurement and provides guidelines for the support and implementation of these requirements.

The purpose of this document is to describe the use of the invoice and credit note messages as used by Singapore in the PEPPOL network, and to facilitate an efficient implementation and increased use of electronic collaboration


.Statement of copyright
****
This PEPPOL Business Interoperability Specification (PEPPOL BIS) document is a Core Invoice Usage Specification (CIUS) based on CEN/EN 16931:2017. The restrictions on CEN/EN 16931:2017 implemented in this PEPPOL BIS appear from the conformance statement provided in appendix A.

The copyright of CEN/EN 16931:2107 is owned by CEN and its members - the European National Standards Bodies. A copy of CEN/EN 16931-1:2017 may be obtained free of charge from any CEN member.

OpenPEPPOL AISBL holds the copyright of this PEPPOL BIS, developed and published subject to the conditions of the agreement between the European Commission and CEN allowing derivate works to be developed and distributed with no additional licensing requirements. CEN and the National  Standards Bodies bears no liability from the content and implementation of this PEPPOL BIS.

This PEPPOL BIS document may not be modified, re-distribute, sold or repackaged in any other way without the prior consent of OpenPEPPOL AISBL.
****

== Audience

The audience for this document is organisations wishing to be PEPPOL enabled for exchanging electronic invoices, and/or their ICT-suppliers. These organisations may be:

     * Service providers
     * Contracting Authorities (CA)
     * Economic Operators (EO)
     * Software Developers

More specifically, roles addressed are the following:

    * ICT Architects
    * ICT Developers
    * Business Experts

For further information on PEPPOL/OpenPEPPOL, please see {common}
