[preface]
= Introduction to openPeppol and BIS
This specification is an extension of the Peppol BIS Billing 3.0 specification, following the guidance given in TR 16931-5 “Guidelines on the use of sector or country extensions in conjunction with EN16931-1” Any instance documents compliant to this specification will be conformant to the Peppol BIS Billing 3.0 and to the European Standard EN 16931.

The main requirement for the extensions comes from the fact that Singapore uses Goods and Service Tax (GST) instead of Value Added Tax (VAT). This has consequences on code lists and the naming of some business terms. In addition to GST this specification also supports typical Singapore payment methods (PayNow and Giro).

On a syntactical level, this specification uses the OASIS UBL 2.1 XML format.

A {peppol} BIS provides a set of specifications for implementing a {peppol} business process. A BIS document is concerned with clarifying requirements for ensuring interoperability between business partners and provides guidelines for the support and implementation of these requirements.

The purpose of this document is to describe the use of the invoice and credit note messages as used by Singapore in the Peppol network, and to facilitate an efficient implementation and increased use of electronic collaboration.

.Statement of copyright
****
This Peppol Business Interoperability Specification (Peppol BIS) document is an extension of Peppol BIS Billing 3 (and consequently CEN/EN 16931:2017).

The copyright of CEN/EN 16931:2107 is owned by CEN and its members - the European National Standards Bodies. A copy of CEN/EN 16931-1:2017 may be obtained free of charge from any CEN member.

OpenPeppol AISBL holds the copyright of this Peppol BIS, developed and published subject to the conditions of the agreement between the European Commission and CEN allowing derivate works to be developed and distributed with no additional licensing requirements. CEN and the National  Standards Bodies bears no liability from the content and implementation of this Peppol BIS.

This Peppol BIS document may not be modified, re-distribute, sold or repackaged in any other way without the prior consent of OpenPeppol AISBL.
****


== Document Structure

This document is structured as follows:

*	*Chapters 1 - 5* gives general information on the business processes, requirements and functionalities
*	*Chapter 6* describes the semantical data types
*	*Chapters 7 - 9* describes GST, calculations and rounding.
*	*Chapter 10* provides examples of selected parts of the invoice
*	*Chapter 11* gives details and links to all code lists used
*   *Chapter 12* gives information on Peppol identifiers
*	*Chapter 13* describes in detail central information elements.
*	*Chapters 14 and 15* provides information on validation and validation rules


== Scope

This document is concerned with clarifying requirements for ensuring interoperability  and provides guidelines for the support and implementation of these requirements. This document will also provide a detailed implementation guideline for the invoice and credit note transactions.

== Audience

The audience for this document is organisations wishing to be Peppol enabled for exchanging electronic invoices, and/or their ICT-suppliers. These organisations may be:

     * Service providers
     * Contracting Authorities (CA)
     * Economic Operators (EO)
     * Software Developers

More specifically, roles addressed are the following:

    * ICT Architects
    * ICT Developers
    * Business Experts

For further information on Peppol/OpenPeppol, please see {common}
